### PR TITLE
Default RNG + Exception Handling + Zero seed avoidance

### PR DESCRIPTION
**Pull request by theonlynavin**
Similar to random.next(), random.next_int(), etc in python, now diceforge has a static singleton XORShift as the default RNG.
You should be able to use random()->next(), random()->shuffle(), etc. in DiceForge now

### CODE REVIEW

**Comment by Prad-R** [comment]
Naor-Reingold bug just got fixed by advik. So maybe you can remove that from the priority list.

**Comment by theonlynavin** [comment]
I've made the changes

**Comment by Prad-R** [comment]
Uh, geometric has also been completed. Both documentation and source code

**Comment by theonlynavin** [comment]
Accept this PR for now, it has stuff other than the README as well.

I'll send a new PR for the README

**Comment by Prad-R** [comment]
Parijat's latest PR has a conflict with this one. I'm closing this PR, open another one.

**Pull request closed without merging**
